### ISSUE TITLE
Variabili con caratteri speciali non ammessi

### ISSUE THREAD

**Issue by gianluca-pepe** [obdasystems/sparqling-ws#26]
Le entità nel query-graph con la label che contiene caratteri speciali ( spazio, -, $, @ ecc..) portano alla creazione di variabili del tipo `?E-Book0` che mandano in errore il parser della query sparql su qualsiasi altra chiamata successiva.

**Comment by giacomoronconiobda** [comment]
Dovrei aver risolto
