### ISSUE TITLE
La chiusura transitiva non suggerisce alcuni ruoli

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/sparqling-ws#29]
Nell'ontologia in allegatocliccando su `https://w3id.org/italia/onto/ITO/Unita_territoriale_sovracomunale` dovrebbero essere suggeriti anche dei ruoli (`https://w3id.org/italia/onto/ITO/attuale_unita_amministrativa_di_origine`) perché relativi al padre `https://w3id.org/italia/onto/ITO/Unita_amministrativa`. 

La cosa strana è che per esempio il ruolo `https://w3id.org/italia/onto/ITO/ha_storico_di_unita_amministrativa` viene correttamente suggerito.

![image](https://user-images.githubusercontent.com/36189778/210829461-5e7456da-6ee6-48b8-821e-508e3daa4e51.png)
Ontologia: 
https://github.com/obdasystems/istat-ndc/blob/main/ProcedureSDG/OntologieGenerali/territorio/italianTerritoryOntology_v1.1.graphol

**Comment by giacomoronconiobda** [comment]
Piano di azione: 
- Togliere tutto tranne:
  - Ruolo ciclico (https://w3id.org/italia/onto/ITO/attuale_unita_amministrativa_di_origine)
  - Gerarchie di Unità amministrativa
  - Lasciare assiomi con il not (https://w3id.org/italia/onto/ITO/appartiene_attualmente_a_regione, https://w3id.org/italia/onto/ITO/appartiene_attualmente_a_UTS)

**Comment by NonnonePalmiro** [comment]
Il bug è stato risolto, ma per correggerlo è stato necessario apportare modifiche che invalidano i test in `com.obdasystems.sparqling.engine.TestPolymorphProperties`.

Per risolvere credo sia necessario modificare opportunamente codice metodo `getHighlights` della classe `OntologyProximityManager` . Valutare se intervenire immediatamente, dato che potrebbe essere necessario tenere conto di output della issue https://github.com/obdasystems/sparqling-ws/issues/31
