### ISSUE TITLE
Filtri di una variabile non vengono eliminati all'eliminazione della variabile oggetto

### ISSUE THREAD

**Issue by gianluca-pepe** [obdasystems/sparqling-ws#35]
**Passi per riprodurre**
- Elimina attributo con filtro
- Aggiungi stesso attributo -> ha il filtro precedente, non dovrebbe avere alcun filtro
- Elimina filtro da query head -> viene aggiunto di nuvo

**Comment by gianluca-pepe** [comment]
Sembra un problema backend, in questo punto il substring alla riga 319 non permette poi il match successivo sui filtri da eliminare impedendo quindi l'eliminazione dei filtri all'eliminazione della variabile.

https://github.com/obdasystems/sparqling-ws/blob/6aeefd706f2f07421dede5a3f25db4fcacc0c09f/src/main/java/com/obdasystems/sparqling/query/QueryGraphHandler.java#L315-L327

**Comment by giacomoronconiobda** [comment]
Sembra che questo fix invalidi il `TestQueryGraphHandler.testIssue16`
